name: desafio_target_sistemas
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0-149.3.beta

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get_it: ^9.2.0
  flutter_screenutil: ^5.9.3
  mobx: ^2.5.0
  shared_preferences: ^2.5.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner:
  mobx_codegen: ^2.7.4

flutter:
  uses-material-design: true
